name: Booking Service Production CI

on:
  push:
    branches:
      - main
      - develop
      - feature/ci-booking
  pull_request:
    branches:
      - main
      - develop

jobs:
  # 1. Code Quality
  sonarqube:
    uses: QuickHaulTransits/quickhaul-shared/.github/workflows/_sonarqube.yml@feature/templates
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  # 2. Dependency Scan
  snyk:
    needs: sonarqube
    uses: QuickHaulTransits/quickhaul-shared/.github/workflows/_snyk.yml@feature/templates
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  # 3. Build & Push
  ghcr:
    needs: snyk
    if: github.event_name == 'push'
    uses: QuickHaulTransits/quickhaul-shared/.github/workflows/_docker-ci.yml@feature/templates
    with:
      image-name: quickhaul-booking
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  # 4. Container Scan
  trivy:
    needs: ghcr
    if: github.event_name == 'push'
    uses: QuickHaulTransits/quickhaul-shared/.github/workflows/_trivy.yml@feature/templates
    with:
      image-name: quickhaul-booking
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
